{% set version = "1.0-2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rioja
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rioja_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rioja/rioja_{{ version }}.tar.gz
  sha256: 54f468c1309138aea2e87adad58b2390133f4d026e8ac03beab94dcc7e369ca6

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dplyr
    - r-forcats
    - r-mgcv
    - r-sjmisc
    - r-stringr
    - r-vegan
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-dplyr
    - r-forcats
    - r-mgcv
    - r-sjmisc
    - r-stringr
    - r-vegan

test:
  commands:
    - $R -e "library('rioja')"           # [not win]
    - "\"%R%\" -e \"library('rioja')\""  # [win]

about:
  home: http://www.staff.ncl.ac.uk/stephen.juggins/
  dev_url: https://github.com/nsj3/rioja
  license: GPL-2.0-only
  summary: Stratigraphic diagrams, constrained clustering, transfer functions, and other methods for analysing Quaternary science data.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
