{% set version = '0.9-21' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rioja
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rioja_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rioja/rioja_{{ version }}.tar.gz
  sha256: 65dec867832541a61041a4909678653fdf67506f6aa49e41cced8fc0dd3f6c07

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mgcv
    - r-vegan
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-mgcv
    - r-vegan

test:
  commands:
    - $R -e "library('rioja')"           # [not win]
    - "\"%R%\" -e \"library('rioja')\""  # [win]

about:
  home: http://www.staff.ncl.ac.uk/stephen.juggins/
  license: GPL-2
  summary: Constrained clustering, transfer functions, and other methods for analysing Quaternary
    science data.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rioja
# Type: Package
# Title: Analysis of Quaternary Science Data
# Version: 0.9-21
# Date: 2019-04-23
# Author: Steve Juggins
# Maintainer: Steve Juggins <Stephen.Juggins@ncl.ac.uk>
# Imports: vegan, mgcv, grDevices
# Suggests: maptools, foreach
# Description: Constrained clustering, transfer functions, and other methods for analysing Quaternary science data.
# License: GPL-2
# URL: http://www.staff.ncl.ac.uk/stephen.juggins/
# NeedsCompilation: yes
# Repository: CRAN
# Packaged: 2019-04-23 17:53:25 UTC; nsj3
# Date/Publication: 2019-04-23 21:22:02
